common_reduce_ops:
- gen: true
  param_map:
    META:
      BLOCK_SIZE: block_n
    num_warps: 1
    num_stages: nstages
  block_n:
  - 1024
  - 2048
  - 4096
  - 8192
  - 16384
  - 32768
  - 65536
  nstages:
  - 1
  - 3
#######################################
bmm:
- META:
    TILE_M: 32
    TILE_N: 32
    TILE_K: 32
    GROUP_M: 1
  num_warps: 4
  num_stages: 2
- META:
    TILE_M: 64
    TILE_N: 32
    TILE_K: 32
    GROUP_M: 2
  num_warps: 4
  num_stages: 2
- META:
    TILE_M: 64
    TILE_N: 64
    TILE_K: 32
    GROUP_M: 2
  num_warps: 4
  num_stages: 2
- META:
    TILE_M: 128
    TILE_N: 32
    TILE_K: 32
    GROUP_M: 2
  num_warps: 4
  num_stages: 2
- META:
    TILE_M: 128
    TILE_N: 64
    TILE_K: 32
    GROUP_M: 2
  num_warps: 4
  num_stages: 2
- META:
    TILE_M: 128
    TILE_N: 128
    TILE_K: 32
    GROUP_M: 2
  num_warps: 4
  num_stages: 2
- META:
    TILE_M: 32
    TILE_N: 32
    TILE_K: 32
    GROUP_M: 1
  num_warps: 4
  num_stages: 3
- META:
    TILE_M: 64
    TILE_N: 32
    TILE_K: 32
    GROUP_M: 2
  num_warps: 4
  num_stages: 3
- META:
    TILE_M: 64
    TILE_N: 64
    TILE_K: 32
    GROUP_M: 2
  num_warps: 4
  num_stages: 3
- META:
    TILE_M: 128
    TILE_N: 32
    TILE_K: 32
    GROUP_M: 2
  num_warps: 4
  num_stages: 3
- META:
    TILE_M: 128
    TILE_N: 64
    TILE_K: 32
    GROUP_M: 2
  num_warps: 4
  num_stages: 3
- META:
    TILE_M: 128
    TILE_N: 128
    TILE_K: 32
    GROUP_M: 2
  num_warps: 4
  num_stages: 3
- META:
    TILE_M: 64
    TILE_N: 64
    TILE_K: 64
    GROUP_M: 2
  num_warps: 1
  num_stages: 3
- META:
    TILE_M: 128
    TILE_N: 384
    TILE_K: 64
    GROUP_M: 2
  num_warps: 1
  num_stages: 3
- META:
    TILE_M: 128
    TILE_N: 256
    TILE_K: 128
    GROUP_M: 2
  num_warps: 1
  num_stages: 3
- META:
    TILE_M: 256
    TILE_N: 256
    TILE_K: 128
    GROUP_M: 2
  num_warps: 1
  num_stages: 3
- META:
    TILE_M: 128
    TILE_N: 1024
    TILE_K: 128
    GROUP_M: 2
  num_warps: 4
  num_stages: 3
- META:
    TILE_M: 256
    TILE_N: 1024
    TILE_K: 128
    GROUP_M: 2
  num_warps: 4
  num_stages: 3
- META:
    TILE_M: 64
    TILE_N: 448
    TILE_K: 128
    GROUP_M: 2
  num_warps: 1
  num_stages: 3
- META:
    TILE_M: 128
    TILE_N: 448
    TILE_K: 128
    GROUP_M: 2
  num_warps: 1
  num_stages: 3
#######################################
argmax:
- gen: true
  param_map:
    META:
      BLOCK_M: block_m
      BLOCK_N: block_n
    num_warps: 1
    num_stages: 3
  block_m:
  - 4
  - 8
  block_n:
  - 4096
  - 8192
  - 16384

argmax_kernel_1:
- gen: true
  param_map:
    META:
      BLOCK_SIZE: block_s
    num_warps: 1
    num_stages: nstage
  nstage:
  - 1
  - 3
  block_s:
  - 4096
  - 8192
  - 16384
  - 32768
  - 65536
  - 131072
#######################################
log_softmax:
- gen: true
  param_map:
    META:
      BLOCK_M: block_m
      BLOCK_N: block_n
    num_warps: 1
    num_stages: nstage
  nstage:
  - 1
  - 3
  block_m:
  - 1
  - 2
  - 4
  - 8
  block_n:
  - 1024
  - 2048
  - 4096
  - 8192
  - 16384
#######################################
mm:
- META:
    BLOCK_M: 128
    BLOCK_N: 128
    BLOCK_K: 128
    SPLIT_K: 1
  num_stages: 4
  num_warps: 1
- META:
    BLOCK_M: 256
    BLOCK_N: 128
    BLOCK_K: 128
    SPLIT_K: 1
  num_stages: 4
  num_warps: 1
- META:
    BLOCK_M: 256
    BLOCK_N: 256
    BLOCK_K: 128
    SPLIT_K: 1
  num_stages: 4
  num_warps: 1
- META:
    BLOCK_M: 256
    BLOCK_N: 1024
    BLOCK_K: 64
    SPLIT_K: 1
  num_stages: 1
  num_warps: 4
- META:
    BLOCK_M: 64
    BLOCK_N: 512
    BLOCK_K: 128
    SPLIT_K: 1
  num_stages: 4
  num_warps: 4
- META:
    BLOCK_M: 128
    BLOCK_N: 512
    BLOCK_K: 128
    SPLIT_K: 1
  num_stages: 4
  num_warps: 4
- META:
    BLOCK_M: 256
    BLOCK_N: 512
    BLOCK_K: 128
    SPLIT_K: 1
  num_stages: 4
  num_warps: 4
- META:
    BLOCK_M: 256
    BLOCK_N: 1024
    BLOCK_K: 128
    SPLIT_K: 1
  num_stages: 4
  num_warps: 4
- META:
    BLOCK_M: 64
    BLOCK_N: 64
    BLOCK_K: 64
    SPLIT_K: 1
  num_stages: 4
  num_warps: 1
- META:
    BLOCK_M: 64
    BLOCK_N: 64
    BLOCK_K: 64
    SPLIT_K: 1
  num_stages: 4
  num_warps: 1
- META:
    BLOCK_M: 64
    BLOCK_N: 64
    BLOCK_K: 384
    SPLIT_K: 1
  num_stages: 1
  num_warps: 1
- META:
    BLOCK_M: 768
    BLOCK_N: 64
    BLOCK_K: 256
    SPLIT_K: 1
  num_stages: 4
  num_warps: 4
- META:
    BLOCK_M: 192
    BLOCK_N: 128
    BLOCK_K: 256
    SPLIT_K: 1
  num_stages: 4
  num_warps: 1
- META:
    BLOCK_M: 256
    BLOCK_N: 768
    BLOCK_K: 256
    SPLIT_K: 1
  num_stages: 4
  num_warps: 4
- META:
    BLOCK_M: 256
    BLOCK_N: 128
    BLOCK_K: 128
    SPLIT_K: 1
  num_stages: 4
  num_warps: 1
- META:
    BLOCK_M: 256
    BLOCK_N: 512
    BLOCK_K: 256
    SPLIT_K: 1
  num_stages: 5
  num_warps: 4
- META:
    BLOCK_M: 128
    BLOCK_N: 512
    BLOCK_K: 256
    SPLIT_K: 1
  num_stages: 5
  num_warps: 4
#######################################
softmax_non_inner:
- META:
    TILE_K: 32
- META:
    TILE_K: 64
- META:
    TILE_K: 128
- META:
    TILE_K: 256
- META:
    TILE_K: 1024
softmax_inner:
- META:
    TILE_N: 32
- META:
    TILE_N: 64
- META:
    TILE_N: 128
- META:
    TILE_N: 256
- META:
    TILE_N: 1024
#######################################
test_libentry:
- META:
    TILE_N: 32
- META:
    TILE_N: 64
- META:
    TILE_N: 128
- META:
    TILE_N: 256
- META:
    TILE_N: 512
- META:
    TILE_N: 1024
#######################################
min:
- META:
    BLOCK_M: 8
    BLOCK_N: 256
  num_warps: 8
- META:
    BLOCK_M: 16
    BLOCK_N: 512
  num_warps: 8
- META:
    BLOCK_M: 32
    BLOCK_N: 512
  num_warps: 8
#######################################
prod:
- META:
    BLOCK_M: 8
    BLOCK_N: 256
  num_warps: 8
- META:
    BLOCK_M: 16
    BLOCK_N: 512
  num_warps: 8
- META:
    BLOCK_M: 32
    BLOCK_N: 512
  num_warps: 8
#######################################
max:
- META:
    BLOCK_M: 8
    BLOCK_N: 256
  num_warps: 1
- META:
    BLOCK_M: 16
    BLOCK_N: 512
  num_warps: 1
- META:
    BLOCK_M: 32
    BLOCK_N: 512
  num_warps: 1
#######################################
addmm:
- META:
    BLOCK_SIZE_M: 128
    BLOCK_SIZE_N: 128
    BLOCK_SIZE_K: 128
  num_stages: 4
  num_warps: 1
- META:
    BLOCK_SIZE_M: 256
    BLOCK_SIZE_N: 128
    BLOCK_SIZE_K: 128
  num_stages: 4
  num_warps: 1
- META:
    BLOCK_SIZE_M: 256
    BLOCK_SIZE_N: 256
    BLOCK_SIZE_K: 128
  num_stages: 4
  num_warps: 1
- META:
    BLOCK_SIZE_M: 256
    BLOCK_SIZE_N: 1024
    BLOCK_SIZE_K: 64
  num_stages: 4
  num_warps: 1
- META:
    BLOCK_SIZE_M: 64
    BLOCK_SIZE_N: 512
    BLOCK_SIZE_K: 128
  num_stages: 4
  num_warps: 4
- META:
    BLOCK_SIZE_M: 128
    BLOCK_SIZE_N: 512
    BLOCK_SIZE_K: 128
  num_stages: 4
  num_warps: 4
- META:
    BLOCK_SIZE_M: 256
    BLOCK_SIZE_N: 512
    BLOCK_SIZE_K: 128
  num_stages: 4
  num_warps: 4
- META:
    BLOCK_SIZE_M: 256
    BLOCK_SIZE_N: 1024
    BLOCK_SIZE_K: 128
  num_stages: 4
  num_warps: 4
- META:
    BLOCK_SIZE_M: 64
    BLOCK_SIZE_N: 64
    BLOCK_SIZE_K: 64
  num_stages: 4
  num_warps: 1
- META:
    BLOCK_SIZE_M: 64
    BLOCK_SIZE_N: 64
    BLOCK_SIZE_K: 384
  num_stages: 1
  num_warps: 1
- META:
    BLOCK_SIZE_M: 768
    BLOCK_SIZE_N: 64
    BLOCK_SIZE_K: 256
  num_stages: 4
  num_warps: 4
- META:
    BLOCK_SIZE_M: 192
    BLOCK_SIZE_N: 128
    BLOCK_SIZE_K: 256
  num_stages: 4
  num_warps: 1
- META:
    BLOCK_SIZE_M: 256
    BLOCK_SIZE_N: 768
    BLOCK_SIZE_K: 256
  num_stages: 4
  num_warps: 4
- META:
    BLOCK_SIZE_M: 256
    BLOCK_SIZE_N: 128
    BLOCK_SIZE_K: 128
  num_stages: 4
  num_warps: 1
- META:
    BLOCK_SIZE_M: 256
    BLOCK_SIZE_N: 512
    BLOCK_SIZE_K: 256
  num_stages: 5
  num_warps: 4
- META:
    BLOCK_SIZE_M: 128
    BLOCK_SIZE_N: 512
    BLOCK_SIZE_K: 256
  num_stages: 5
  num_warps: 4
#######################################
cross_entropy_loss:
- gen: true
  param_map:
    META:
      BLOCK_C: block_c
      BLOCK_D: block_d
    num_warps: 1
  block_c:
  - 256
  - 512
  - 1024
  block_d:
  - 1
  - 4
  - 16
#######################################
upsample_nearest2d:
- gen : true
  param_map:
    META:
      BLOCK_SIZE: block_n
    num_warps: warps
  block_n: [1024, 2048, 4096, 8192, 16384]
  warps: [1]
#######################################
masked_fill:
- gen: true
  param_map:
    META:
      BLOCK_SIZE: block_n
    num_warps: 1
  block_n:
  - 1024
  - 2048
  - 4096
  - 8192
  - 16384
#######################################
all:
- gen: true
  param_map:
    META:
      BLOCK_M: block_m
      BLOCK_N: block_n
    num_warps: 1
  block_m:
  - 1
  - 2
  - 4
  - 8
  - 16
  - 32
  block_n:
  - 512
  - 1024
#######################################
amax_kernel:
- gen: true
  param_map:
    META:
      BLOCK_M: block_m
      BLOCK_N: block_n
    num_warps: 1
    num_stages: 3
  block_m:
  - 1
  - 2
  - 4
  - 8
  block_n:
  - 1024
  - 2048
  - 4096

amax_kernel_opt:
- gen: true
  param_map:
    META:
      TILE_NUM_N: tile_num_n
    num_warps: 1
    num_stages: nstage
  tile_num_n:
  - 1
  - 2
  - 4
  - 8
  - 16
  - 48
  nstage:
  - 1
  - 3
#######################################
any:
- gen: true
  param_map:
    META:
      BLOCK_M: block_m
      BLOCK_N: block_n
    num_warps: 1
  block_m:
  - 1
  - 2
  - 4
  - 8
  - 16
  - 32
  block_n:
  - 512
  - 1024
#######################################
index_select:
- gen: true
  param_map:
    META:
      BLOCK_BATCH: block_b
      BLOCK_INDEX: block_i
      BLOCK_C: block_c
    num_warps: 1
    num_stages: 1
  block_b:
  - 1
  - 4
  - 8
  - 16
  - 32
  block_i:
  - 1
  - 8
  - 16
  - 32
  - 64
  block_c:
  - 256
  - 512
  - 1024
  - 2048
#######################################
layer_norm_persistent:
- gen: true
  param_map:
    META:
      BLOCK_ROW_SIZE: brs
    num_warps: 1
    num_stages: nstags
  brs:
  - 1
  - 2
  - 4
  - 8
  - 12
  - 18
  - 22
  - 32
  nstags:
  - 1
  - 3
#######################################
layer_norm_loop:
- gen: true
  param_map:
    META:
      BLOCK_ROW_SIZE: brs
      BLOCK_COL_SIZE: bcs
    num_warps: 1
    num_stages: nstages
  nstages:
  - 1
  - 3
  brs:
  - 1
  - 2
  - 8
  - 14
  - 22
  bcs:
  - 64
  - 128
  - 256
  - 512
  - 1024
  - 5120
#######################################
layer_norm_backward:
- gen: true
  param_map:
    META:
      BLOCK_ROW_SIZE: block_r
      BLOCK_COL_SIZE: 2048
    num_warps: warps
  warps:
  - 4
  - 8
  - 16
  block_r:
  - 1
  - 2
  - 4
  - 8
#######################################
weight_bias_backward:
- gen: true
  param_map:
    META:
      BLOCK_ROW_SIZE: 2048
      BLOCK_COL_SIZE: block_c
    num_warps: warps
  warps:
  - 4
  - 8
  - 16
  block_c:
  - 1
  - 2
  - 4
  - 8
#######################################
masked_select:
- gen: true
  param_map:
    META:
      BLOCK_SIZE: blocks
    num_warps: 1
  blocks:
  - 64
  - 256
  - 512
  - 1024
  - 2048
  - 4096
  - 8192
  - 16384
  - 32768
#######################################
mean:
- gen: true
  param_map:
    META:
      BLOCK_M: block_m
      BLOCK_N: 1024
    num_warps: 4
  block_m:
  - 1
  - 2
  - 4
  - 8
#######################################
instancenorm:
- gen: true
  param_map:
    META: {}
    num_warps: warps
  warps:
  - 4
  - 8
  - 16

instance_norm_loop:
- gen: true
  param_map:
    META:
      TILE_N: tile_n
    num_warps: warps
  warps:
    - 4
    - 8
    - 16
  tile_n:
    - 1024
    - 2048
    - 4096
    - 8192

instance_norm_backward:
- gen : true
  param_map:
    META:
      BLOCK_ROW_SIZE: block_m
      BLOCK_COL_SIZE: 2048
    num_warps: warps
  warps:
    - 4
    - 8
    - 16
  block_m:
    - 1
    - 2
    - 4
    - 8

instance_norm_weight_bias_backward:
- gen : true
  param_map:
    META:
      BLOCK_BATCH_SIZE: block_m
      BLOCK_COL_SIZE: 2048
    num_warps: warps
  warps:
    - 4
    - 8
    - 16
  block_m:
    - 1
    - 2
    - 4
    - 8
#######################################
count_nonzero:
- gen : true
  param_map:
    META:
      BLOCK_SIZE: block_m
    num_warps: 1
  block_m:
    - 1024
    - 2048
    - 4096
#######################################
cross_entropy_loss_sum_and_scale:
- gen : true
  param_map:
    META:
      BLOCK_N: block_n
  block_n:
  - 64
  - 256
  - 1024
#######################################
upsample_bicubic2d_aa:
- gen : true
  param_map:
    META:
      BLOCK_X: block_x
      BLOCK_Y: block_y
    num_warps: warps
  block_x: [512, 256, 128, 64]
  block_y: [2, 1]
  warps: [4, 8]
#######################################
mv:
- gen: true
  param_map:
    META:
      BLOCK_M: block_m
      BLOCK_N: block_n
    num_warps: 1
    num_stages: stages
  block_m:
  - 64
  - 128
  - 256
  - 512
  - 1024
  block_n:
  - 16
  - 32
  - 64
  - 128
  stages:
  - 1
  - 3
#######################################
nonzero:
- gen: true
  param_map:
    META:
      BLOCK_SIZE: blocks
    num_warps: warps
    num_stages: 1
  warps:
  - 1
  blocks:
  - 256
  - 512
  - 1024
  - 2048
  - 4096
  - 8192
  - 32768
  - 65536
#######################################
randperm:
- gen: true
  param_map:
    META: {}
    num_warps: warps
  warps:
  - 1
#######################################
select_scatter:
- gen: true
  param_map:
    META:
      BLOCK_M: block_m
      BLOCK_N: 1024
    num_warps: 1
  block_m:
  - 1
  - 2
  - 4
  - 8
  - 16
  - 32
#######################################
select_scatter_inner:
- META:
    R: 1
    C: 512
  num_warps: 1
- META:
    R: 32
    C: 32
  num_warps: 1
- META:
    R: 64
    C: 64
  num_warps: 1
- META:
    R: 4
    C: 512
  num_warps: 1
- META:
    R: 16
    C: 128
  num_warps: 1
#######################################
softmax:
- META:
    TILE_K: 32
- META:
    TILE_K: 64
- META:
    TILE_K: 128
- META:
    TILE_K: 256
- META:
    TILE_K: 512
- META:
    TILE_K: 1024
#######################################
vstack:
- gen: true
  param_map:
    META:
      BLOCK_SIZE: blocks
    num_warps: warps
  warps:
  - 4
  - 8
  - 16
  - 32
  blocks:
  - 512
  - 1024
  - 2048
  - 4096
#######################################
gather:
- gen: true
  param_map:
    META:
      BLOCK_SIZE: block_s
    num_warps: 1
    num_stages: 1
  block_s:
  - 128
  - 256
  - 512
  - 1024
  - 2048
  - 4096
  - 8192
  - 16384
  - 32768
#######################################
scatter:
- gen: true
  param_map:
    META:
      BLOCK_SIZE: block_s
    num_warps: 1
    num_stages: 1
  block_s:
  - 64
  - 128
  - 256
  - 384
  - 512
  - 768
  - 896
  - 1024
  - 2048
  - 4096
  - 8192
  - 16384
  - 32768
#######################################
sum:
- gen: true
  param_map:
    META:
      BLOCK_M: block_m
      BLOCK_N: block_n
    num_warps: 1
  block_m:
  - 1
  - 2
  - 4
  - 8
  - 16
  - 32
  block_n:
  - 512
  - 1024
#######################################
triu:
- META:
    M_BLOCK_SIZE: 1
  num_warps: 1
  num_stages: 3
- META:
    M_BLOCK_SIZE: 4
  num_warps: 1
  num_stages: 3
- META:
    M_BLOCK_SIZE: 8
  num_warps: 1
  num_stages: 3
- META:
    M_BLOCK_SIZE: 16
  num_warps: 1
  num_stages: 3
#######################################
triu_batch:
- gen: true
  param_map:
    META:
      BATCH_BLOCK_SIZE: 1
      MN_BLOCK_SIZE: 512
    num_warps: warps
  warps:
  - 1
#######################################
weight_norm_kernel_last:
- gen: true
  param_map:
    META:
      BLOCK_ROW_SIZE: block_m
      BLOCK_COL_SIZE: block_n
    num_warps: warps
  warps:
  - 1
  - 4
  block_m:
  - 512
  - 1024
  - 2048
  block_n:
  - 1
  - 2
  - 4
  - 8
  - 32

weight_norm_kernel_first:
- gen: true
  param_map:
    META:
      BLOCK_ROW_SIZE: block_m
      BLOCK_COL_SIZE: block_n
    num_warps: warps
  warps:
  - 1
  - 4
  block_m:
  - 1
  - 2
  - 4
  - 8
  - 16
  - 32
  block_n:
  - 512
  - 1024
  - 2048

weight_norm_kernel:
- gen: true
  param_map:
    META:
      BLOCK_ROW_SIZE: block_m
      BLOCK_COL_SIZE: block_n
    num_warps: warps
  warps:
  - 1
  block_m:
  - 1
  - 2
  - 4
  - 8
  - 32
  block_n:
  - 256
  - 512
  - 1024
  - 4096
#######################################
vector_norm:
- gen: true
  param_map:
    META:
      BLOCK_M: block_m
      BLOCK_N: 1024
    num_warps: 1
  block_m:
  - 1
  - 2
  - 4
  - 8
#######################################
var_mean:
- gen: true
  param_map:
    META:
      BLOCK_M: block_m
      BLOCK_N: block_n
    num_warps: warps
  block_m:
  - 1
  - 2
  - 4
  - 8
  block_n:
  - 1024
  - 2048
  warps:
  - 1
